using System;
namespace SureMeasure.Common
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	public static class IconFont
	{
		public const string AdjustContrast = "\ue001";
		public const string FitPage = "\uE759";
		public const string Plus = "\uE948";
		public const string Minus = "\uE949";
		public const string Remove = "\uE947";
		public const string Device = "\uE957";
		public const string EditPage = "\uEB7E";
		public const string OrderPage = "\uE779";
		public const string InfoPage = "\uE946";
		public const string Bluetooth = "\uE702";
		public const string Phone = "\uEC7E";
		public const string Car = "\uE804";
		public const string Share = "\uE725";
		public const string Undo = "\uE7A7";
		public const string Redo = "\uE7A6";
		public const string PhoneBook = "\uE780";
		public const string Camera = "\uE722";
		public const string PhotoGallery = "\uE7C5";
		public const string Calculator = "\uE8EF";
		public const string Map = "\uE707";
	}
}
